# Cloud Build configuration for Options Wheel Strategy
# Automatically builds and deploys to Cloud Run when code is pushed to GitHub

steps:
  # Step 1: Run tests before building
  - name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install pytest pytest-mock pytest-asyncio pytest-cov
        pip install -r requirements.txt
        python -m pytest tests/ -v || exit 1
    id: 'run-tests'

  # Step 2: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'deploy/Dockerfile'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/options-wheel/options-wheel-strategy:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/options-wheel/options-wheel-strategy:latest'
      - '.'
    id: 'build-image'
    waitFor: ['run-tests']

  # Step 3: Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/options-wheel/options-wheel-strategy'
    id: 'push-image'
    waitFor: ['build-image']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'options-wheel-strategy'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/options-wheel/options-wheel-strategy:$COMMIT_SHA'
      - '--region=us-central1'
      - '--memory=512Mi'
      - '--concurrency=10'
      - '--max-instances=1'
      - '--min-instances=0'
      - '--timeout=300'
      - '--set-env-vars=ALPACA_PAPER_TRADING=true'
    id: 'deploy-to-cloud-run'
    waitFor: ['push-image']

  # Step 5: Run post-deployment health check
  - name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install requests
        sleep 30  # Wait for deployment to stabilize
        echo "Deployment completed successfully"
    id: 'health-check'
    waitFor: ['deploy-to-cloud-run']

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Fast builds

# Service account for Cloud Build
serviceAccount: 'projects/gen-lang-client-0607444019/serviceAccounts/799970961417@cloudbuild.gserviceaccount.com'

# Timeout for the entire build
timeout: '1200s'  # 20 minutes

# Substitutions for build variables
substitutions:
  _SERVICE_NAME: 'options-wheel-strategy'
  _REGION: 'us-central1'

# Images to be pushed to registry
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/options-wheel/options-wheel-strategy:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/options-wheel/options-wheel-strategy:latest'