# Cloud Build configuration for Options Wheel Strategy
# Automatically builds and deploys to Cloud Run when code is pushed to GitHub

steps:
  # Step 1: Run critical tests only (faster)
  - name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --no-cache-dir pytest pytest-mock pytest-asyncio
        pip install --no-cache-dir alpaca-py pandas numpy structlog pyyaml python-dotenv
        python -m pytest tests/ -v --tb=short || exit 1
    id: 'run-tests'

  # Step 2: Build the trading bot container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'deploy/Dockerfile'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/options-wheel/options-wheel-strategy:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/options-wheel/options-wheel-strategy:latest'
      - '.'
    id: 'build-bot-image'
    waitFor: ['run-tests']

  # Step 3: Build the dashboard container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/options-wheel/options-wheel-dashboard:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/options-wheel/options-wheel-dashboard:latest'
      - '.'
    dir: 'dashboard'
    id: 'build-dashboard-image'
    waitFor: ['run-tests']

  # Step 4: Push the trading bot container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/options-wheel/options-wheel-strategy'
    id: 'push-bot-image'
    waitFor: ['build-bot-image']

  # Step 5: Push the dashboard container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/options-wheel/options-wheel-dashboard'
    id: 'push-dashboard-image'
    waitFor: ['build-dashboard-image']

  # Step 6: Deploy trading bot to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'options-wheel-strategy'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/options-wheel/options-wheel-strategy:$COMMIT_SHA'
      - '--region=us-central1'
      - '--memory=512Mi'
      - '--concurrency=10'
      - '--max-instances=1'
      - '--min-instances=0'
      - '--timeout=300'
      - '--set-env-vars=ALPACA_PAPER_TRADING=true'
    id: 'deploy-bot-to-cloud-run'
    waitFor: ['push-bot-image']

  # Step 7: Deploy dashboard to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'options-wheel-dashboard'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/options-wheel/options-wheel-dashboard:$COMMIT_SHA'
      - '--region=us-central1'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=2'
      - '--min-instances=0'
      - '--timeout=300'
      - '--set-env-vars=TRADING_BOT_URL=https://options-wheel-strategy-799970961417.us-central1.run.app,GCP_PROJECT=$PROJECT_ID'
      - '--allow-unauthenticated'
    id: 'deploy-dashboard-to-cloud-run'
    waitFor: ['push-dashboard-image']

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_32'  # Fastest builds
  diskSizeGb: 100

# Service account for Cloud Build
serviceAccount: 'projects/gen-lang-client-0607444019/serviceAccounts/799970961417@cloudbuild.gserviceaccount.com'

# Timeout for the entire build
timeout: '900s'  # 15 minutes (increased for dashboard build)

# Substitutions for build variables
substitutions:
  _SERVICE_NAME: 'options-wheel-strategy'
  _REGION: 'us-central1'

# Images to be pushed to registry
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/options-wheel/options-wheel-strategy:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/options-wheel/options-wheel-strategy:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/options-wheel/options-wheel-dashboard:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/options-wheel/options-wheel-dashboard:latest'