apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://options-wheel-strategy-799970961417.us-central1.run.app","https://options-wheel-strategy-omnlacz6ia-uc.a.run.app"]'
  labels:
    cloud.googleapis.com/location: us-central1
  name: options-wheel-strategy
  namespace: '799970961417'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 540.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: ezoyfjuejw
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: ALPACA_PAPER_TRADING
          value: 'true'
        - name: ALPACA_API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: alpaca-api-key
        - name: ALPACA_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: alpaca-secret-key
        image: us-central1-docker.pkg.dev/gen-lang-client-0607444019/options-wheel/options-wheel-strategy
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 799970961417-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
