# Options Wheel Strategy Configuration

# Alpaca API Settings
alpaca:
  # Use paper trading by default for safety
  paper_trading: true
  # API credentials (use environment variables)
  api_key_id: "${ALPACA_API_KEY}"
  secret_key: "${ALPACA_SECRET_KEY}"
  
# Trading Strategy Parameters
strategy:
  # Target days to expiration for new positions
  put_target_dte: 7
  call_target_dte: 7
  
  # Delta thresholds for option selection
  put_delta_range: [0.10, 0.20]
  call_delta_range: [0.30, 0.70]

  # CRITICAL: Cost basis protection for covered calls
  # Never sell calls below stock cost basis to avoid guaranteed losses
  # This is automatically enforced in code - strikes below cost basis are rejected
  
  # Minimum premium thresholds (in dollars)
  min_put_premium: 0.50
  min_call_premium: 0.30
  
  # Stock universe criteria (optimized for cloud execution)
  min_stock_price: 10.00  # Lowered to allow high-volume stocks like Ford (F)
  max_stock_price: 400.00
  min_avg_volume: 2000000  # 2M shares daily average for better liquidity
  
  # Maximum positions
  max_positions_per_stock: 1
  max_total_positions: 10
  
  # Maximum exposure per ticker (dollar amount assuming assignment)
  max_exposure_per_ticker: 25000  # $25,000 max exposure per ticker (conservative for cloud)

# Risk Management
risk:
  # Portfolio allocation limits
  max_portfolio_allocation: 0.80  # 80% of portfolio
  max_position_size: 0.35         # 35% per position (allows up to $35k positions)
  min_cash_reserve: 0.20          # 20% cash reserve
  
  # Stop loss settings (separate controls for puts vs calls)
  use_put_stop_loss: false        # Take assignment instead of stopping out puts
  use_call_stop_loss: true        # Still protect covered calls from adverse moves
  put_stop_loss_percent: 0.50     # Put stop loss threshold (ignored if disabled)
  call_stop_loss_percent: 0.50    # Call stop loss threshold
  stop_loss_multiplier: 1.5       # Multiplier for short-term options (accounts for time decay)
  
  # Profit taking settings
  profit_target_percent: 0.50     # 50% profit target for early closure
  
  # Volatility filters
  max_iv_rank: 80                 # Maximum implied volatility rank
  min_iv_rank: 20                 # Minimum implied volatility rank

  # Gap risk management
  gap_risk_controls:
    enable_gap_detection: true    # Enable overnight gap monitoring
    max_overnight_gap_percent: 5.0  # Max 5% overnight gap before position closure
    gap_lookback_days: 30         # Days to analyze historical gap frequency
    max_gap_frequency: 0.15       # Max 15% of days can have significant gaps
    earnings_avoidance_days: 7    # Avoid new positions N days before earnings

    # Quality control thresholds (historical analysis)
    quality_gap_threshold: 2.0    # Threshold for counting "significant gaps" in stock filtering

    # Real-time execution controls (hard filter - more conservative)
    execution_gap_threshold: 1.5  # HARD STOP: Don't execute trades if overnight gap exceeds this
    execution_gap_lookback_hours: 16 # Check gap from previous close (market close to open)

    # Pre-market gap thresholds
    premarket_gap_threshold: 2.0  # 2% pre-market gap triggers review
    market_open_delay_minutes: 15 # Wait 15min after open if gap detected

    # Historical volatility filters
    max_historical_vol: 0.40      # 40% maximum annualized volatility
    vol_lookback_days: 252        # 1 year lookback for volatility calculation

# Stock Universe
stocks:
  # High-quality, liquid stocks suitable for wheel strategy
  # TSLA removed due to extreme volatility and gap risk
  # F (Ford) added - S&P 500 stock with excellent options liquidity at ~$12/share
  symbols:
    - "AAPL"
    - "MSFT"
    - "GOOGL"
    - "AMZN"
    - "NVDA"
    - "AMD"
    - "QQQ"
    - "SPY"
    - "IWM"
    - "UNH"
    - "F"

# Monitoring and Alerts (Cloud-optimized)
monitoring:
  # Check positions every N minutes during market hours
  check_interval_minutes: 15

  # Alert thresholds
  assignment_alert: true
  profit_target_alert: true
  loss_threshold_alert: true

  # Cloud-specific monitoring
  enable_cloud_logging: true
  max_execution_time_minutes: 5  # Cloud Run timeout consideration
  enable_performance_metrics: true
  
# Logging Configuration
logging:
  level: "INFO"
  log_to_file: true
  log_file: "logs/options_wheel.log"
  max_log_size: "10MB"
  backup_count: 5